return {
	CallerIsInAnotherCall = "CallerIsInAnotherCall",
	CalleeIsInAnotherCall = "CalleeIsInAnotherCall",
	PlaceIsNotVoiceEnabled = "PlaceIsNotVoiceEnabled",
	UniverseIsNotVoiceEnabled = "UniverseIsNotVoiceEnabled",
	CallerIsNotVoiceEnabled = "CallerIsNotVoiceEnabled",
	UniverseAgeIsNotValid = "UniverseAgeIsNotValid",
	ReservedServerAccessCodeIsNotProvided = "ReservedServerAccessCodeIsNotProvided",
	CallInitializationTimeout = "CallInitializationTimeout",
	PlatformIsNotSupported = "PlatformIsNotSupported"
}
